name: react-rust-postgres
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust:1-1-bullseye
    command: sleep infinity
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target:/workspace/target
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro
    environment:
      - ADDRESS=0.0.0.0:8080
      - RUST_LOG=debug
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
volumes:
  cargo-cache: {}
  target: {}
  db-data: {}
  redis-data: {}
